/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
C74GenAudioProcessorEditor::C74GenAudioProcessorEditor (C74GenAudioProcessor& p)
    : AudioProcessorEditor (&p), processor (p)
{

    setSize(200, 200);

    // These define the parameter of our slider object
    targetSlider.setSliderStyle(Slider::RotaryHorizontalVerticalDrag);
    targetSlider.setRange(0.0, 1.0, 0.01);
    targetSlider.setTextBoxStyle(Slider::TextBoxBelow, false, 90, 12);
    targetSlider.setPopupDisplayEnabled(false, false, this);
    // targetSlider.setTextValueSuffix(" LKFS");
    targetSlider.setValue(0.46);
    targetSlider.setDoubleClickReturnValue(true, 0.46);

    // this function adds the slider to the editor
    addAndMakeVisible(&targetSlider);

    // add the listener to the slider
    targetSlider.addListener(this);
}

C74GenAudioProcessorEditor::~C74GenAudioProcessorEditor()
{
}

//==============================================================================
void C74GenAudioProcessorEditor::paint (Graphics& g)
{
    //[UserPrePaint] Add your own custom painting code here..
    //[/UserPrePaint]

    g.fillAll(Colour(0xff323e44));

    //[UserPaint] Add your own custom painting code here..
    //[/UserPaint]
}

void C74GenAudioProcessorEditor::resized()
{
    // sets the position and size of the slider with arguments (x, y, width, height)
    targetSlider.setBounds(20, 20, 160, getHeight() - 60);
}

void C74GenAudioProcessorEditor::sliderValueChanged(Slider* slider)
{
    if (slider->getName() == targetSlider.getName())
    {
        processor.setParameter(0, slider->getValue());
    }
}